### ISSUE TITLE
dashes in generated words

### ISSUE THREAD

**Issue by tmbdev** [sethblack/funny-words#4]
Funny-words currently will generate words like "ding-a-ling" and "will-o-wisp", containing dashes. Filenames often use dashes to separate other components, so this will yield a variable number of dashes in the result. That is, file names that should come out as "word-word-number-number.pth" might come out as "word-word-word-word-number-number.pth".

I'd suggest either eliminating words containing dashes from the dictionary, or simply removing the dashes.

**Comment by sethblack** [comment]
Hiya! I agree 💯 

This is the reason for the `--delimiter` option.
